Version: '5.2'
Embedding: T5
Emb_type: global
Model: Epsilon_3
System: b'ev'
Global_seed: 1
conf:
  model_params:
    Model: Epsilon_3
    emb_size: 1024
    projection_layer:
    - 128
    - ln2
    - true
    - 1
    - ''
    output_dim: 1
    input_layer:
    - op-od
    - vanilla
    - lin
    - post_concat
    num_samples: 0
    num_hid_layers:
    - 0
    - 0
    - 0
    - 0
    - vanilla
    - ''
    bias: true
    dropouts:
    - 0.2
    - 0
    - 0
    - 0
    - 0
    norm:
    - true
    - LN
    temperature: null
    output_layer: vanilla
    activation1:
    - elu
    - null
    activation2:
    - sigmoid
    - true
    device: cuda
    objective:
    - interface
    - 1
    - ''
    - false
    - false
    - false
  dataset:
    train_set_size: 0.9
    dev_set_size: 0.05
    test_set_size: 0.05
    model_type: vanilla
    input_files: /data2/kartik/Disorder_Proteins/disobind/Database/v_19/full/T5/global/
    train_file: Train_set_global_v_19.npy
    dev_file: Dev_set_global_v_19.npy
    test_file: Test_set_global_v_19.npy
    output_path: ../Models/Epsilon_2/
    batch_size: 64
    batch_shuffle:
    - true
    - false
    - false
  train_params:
    model_type: vanilla
    objective:
    - interface
    - 1
    - ''
    - false
    - false
    - false
    emb: T5
    confidence: false
    apply_calibration: beta-abm
    invert:
    - 0
    mask:
    - false
    - true
    num_metrics:
    - 7
    - global
    Nruns: 1
    loss: se_loss
    log_weight:
    - - 0.9
      - 3
    optimizer: AdamW
    amsgrad: true
    weight_decay:
    - 0.05
    max_norm: null
    learning_rate:
    - 0.0002
    scheduler:
      apply: true
      name: exp
      milestone:
      - null
      gamma:
      - 0.98
      start_factor: null
      end_factor: null
      total_iters: null
      swa_start: null
      swa_lr: null
      base_lr: null
      step_size_up: null
      step_size_down: null
    max_epochs: 25
    contact_threshold:
    - 0.5
    save_model: true
    model_path: model_global_
    optuna_trials: 0
